[project]
name = "excalibur-server"
version = "0.1.0a9.dev1"
description = "An encrypted file server."
readme = "README.md"
authors = [{ name = "The-Photons" }]
license = "GPL-3.0-or-later"
requires-python = ">=3.11"

dependencies = [
    "aiofiles>=24.1.0",
    "cachetools>=6.1.0",
    "fastapi>=0.116.1",
    "gitpython>=3.1.45",
    "packaging>=25.0",
    "pycryptodome>=3.23.0",
    "pydantic>=2.11.7",
    "pyjwt>=2.10.1",
    "python-multipart>=0.0.20",
    "semver>=3.0.4",
    "toml>=0.10.2",
    "typer~=0.15.4",             # TODO: Update to 0.16.x once the "no_args_is_help causing extra Error box popping up" is fixed
    "uvicorn[standard]>=0.35.0",
    "websockets>=15.0.1",
]

[project.scripts]
excalibur = "excalibur_server.cli:app"

[dependency-groups]
dev = ["ruff>=0.12.7"]
test = ["httpx>=0.28.1", "pytest>=8.4.1"]

[build-system]
requires = ["uv_build>=0.8.0,<0.9"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "excalibur_server"
module-root = ""

[tool.uv.workspace]
members = ["dist/excalibur-server-test"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
extend-select = [
    "E501", # line-too-long
    "C901", # too-complex
]
